### ISSUE TITLE
想问大佬一个问题

### ISSUE THREAD

**Issue by bao-io** [lexiforest/curl_cffi#161]
这个库请求cloudflare保护的网站，有些接口会出现418错误码，用这个库请求的话也绕不过去爬虫检测吗

**Comment by yifeikong** [comment]
TLS 指纹是 CF 检测很重要的一部份，但是不是全部。

**Comment by yifeikong** [comment]
没，我很少搞这种对抗……

**Comment by gospider007** [comment]
> 今天突然不行了，我把cookie、User-agent都加上了，都直接返回418，我不知道我还缺了啥🥹

哪个网站，理论上加了cookie 后应该可以通过的，即使用了其他检测方法
