### ISSUE TITLE
[BUG]fingerprints error

### ISSUE THREAD

**Issue by liuzhijun9509** [lexiforest/curl_cffi#374]
"edge99",
 "edge101",
"chrome99",
"chrome101",
 "chrome107",
 "safari15_3",
更新0.7以后 上面这些指纹依然是异常的
作者能否多更新一些指纹，现在的指纹太少了

**Comment by lexiforest** [comment]
看这里： https://github.com/lexiforest/curl_cffi/blob/main/examples/impersonate.py ，需要的话你可以自定义。

常见浏览器指纹就那么多，我怎么再加 😂

你列的都是很老的浏览器版本了，不好使是正常的。
