### ISSUE TITLE
headers problem

### ISSUE THREAD

**Issue by l7123222l7** [lexiforest/curl_cffi#376]
When I use version 0.6.4, I can leave the request header empty.
For example, changing
upgrade-insecure-requests: 1
to
upgrade-insecure-requests:
This allows me to remove that header
Because XHR interfaces don't have this kind of header
However, in version 0.7.1, when I leave it empty
It displays as follows instead of removing it:

-----------

GET / HTTP/1.1
Host: test.requestcatcher.com
upgrade-insecure-requests:

-----------

But I also realized that some websites have empty headers
For example, Authorization:
It must be included to access, even if it's an empty value
Is there a better way to handle this?

**Comment by lexiforest** [comment]
Yes, we changed that behavior to explicitly include empty-valued headers in 0.7.x. See: 041ff0c

To exclude empty headers, simply filter them out beforehead.

```py
headers = {k: v for k, v in headers.items() if v}
```
