### ISSUE TITLE
请问如何传入一个multipart/form-data数据

### ISSUE THREAD

**Issue by Nekohy** [lexiforest/curl_cffi#378]
似乎和requests,httpx之类的都不一样...实在不知道思路了..所以过来问一下作者，添麻烦了

**Comment by perklet** [comment]
https://github.com/lexiforest/curl_cffi/blob/main/examples/upload.py

**Comment by liesauer** [comment]
how can i just transfer `application/x-www-form-urlencoded` into `multipart/form-data`, i don't have any files to upload
```
------WebKitFormBoundaryO3eLERdmYMli8Y6e
Content-Disposition: form-data; name="verify_code"


------WebKitFormBoundaryO3eLERdmYMli8Y6e
Content-Disposition: form-data; name="type"

0
------WebKitFormBoundaryO3eLERdmYMli8Y6e
```

**Comment by liesauer** [comment]
> how can i just transfer `application/x-www-form-urlencoded` into `multipart/form-data`, i don't have any files to upload
> 
> ```
> ------WebKitFormBoundaryO3eLERdmYMli8Y6e
> Content-Disposition: form-data; name="verify_code"
> 
> 
> ------WebKitFormBoundaryO3eLERdmYMli8Y6e
> Content-Disposition: form-data; name="type"
> 
> 0
> ------WebKitFormBoundaryO3eLERdmYMli8Y6e
> ```

figured out.
