### ISSUE TITLE
[BUG] AsyncSession.base_url uses domain instead of whole init path

### ISSUE THREAD

**Issue by denismur** [lexiforest/curl_cffi#384]
**Code:**
```python
from curl_cffi.requests import AsyncSession

BASE_URL = 'https://example.com/default'

async with AsyncSession(base_url=BASE_URL) as session:
    print(session.base_url)
    response = await session.get('/page', impersonate='chrome')
    print(response.url)
```

**Output:**
```
https://example.com/default
https://example.com/page
```

**Expected output:**
```
https://example.com/default
https://example.com/default/page
```

**Versions**
 - OS: macOS 15.0
 - curl_cffi version 0.7.1

**Comment by lexiforest** [comment]
What you described is actually [the behavior of current `httpx`](https://github.com/encode/httpx/issues/846), which sliently adds an ending slash at the end of base url.

```py
>>> import httpx
>>> c = httpx.Client(base_url="https://example.com/default")
>>> print(c.base_url)
https://example.com/default/
>>> r = c.get("/page")
>>> r.url
URL('https://example.com/default/page')
>>> r = c.get("")
>>> r.url
URL('https://example.com/default/')
```

Actually, I don't think `httpx` behaves correctly, with or without the ending slash can be totally different for some servers, I'm not sure that we should alter the url implicitly.

What curl_cffi did is a simple `urljoin` of the urls you provided, which is what httpx did originally, and I found it is more simple and aligns with the stdlib.

If you want to build an url as what you expected above, you should change your url to:

```py
BASE_URL = 'https://example.com/default/'  # note the ending slash
session.get('page')  # note there is NO leading slash
```

If you have more real world evidence that the current `httpx` behavior is actually more prevelant, feel free to reopen the issue.

**Comment by denismur** [comment]
I switched from httpx and got used to put slash at the beginning of each URL, and for some reason I didn't check slash at the end of base_url. I agree, it's better that way.
