### ISSUE TITLE
[Feature +Bug] Error cipher + websocket work

### ISSUE THREAD

**Issue by Cataphract89** [lexiforest/curl_cffi#390]
1) Bug requests. Faced this problem that I can't expose this cipher when running the latest version of IOS. I saw in another thread that this problem was solved (https://github.com/lexiforest/curl_cffi/issues/355). But it is not working for me. The library version is the latest.

### 
     from curl_cffi import requests as curl_requests
     r = curl_requests.get('https://tls.browserleaks.com/json', ja3='771,4865-4866-4867-49196-49195-52393-49200-49199-52392-49162-49161-49172-49171-157-156-53-47-49160-49170-10,0-23-65281-10-11-16-5-13-18-51-45-43-27-21,29-23-24-25,0')
     print(r.text)
### 
     File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\curl_cffi\requests\session.py", line 257, in _set_ja3_options
    cipher_name = TLS_CIPHER_NAME_MAP[cipher_id]
                  ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
    KeyError: 49160


2) Feature \ Bug websockets. 
The original purpose of the work was to custom impersonate for websocket, when installing ja3 on websocket connection - no errors are given, but the server refuses to establish the connection because of cloudfalre. Successful connection can be established only with ja3 android.
Question 1) Is the websocket setup different from requests in general? 
Question 2) Is there any way to mix ja3 android extensions so that they remain trusted, similar to chrome...

**Comment by perklet** [comment]
For question 1, please wait for the new release. It has been fixed in `main`.

For question 2, please open a new issue. Let's keep one issue focused on one question, thanks.
