### ISSUE TITLE
[BUG] AsyncSession memory leak

### ISSUE THREAD

**Issue by WendyDReid1901** [lexiforest/curl_cffi#406]
AsyncSession 有非常严重的内存泄漏问题，求修复，给100红包。
只有这个库可以拿捏CF拦截，但是没法长期稳定运行，求大佬们出招

**Comment by lexiforest** [comment]
Please provide a minimal reproduible code snippet, otherwise no one will ever know what you are talking about.

**Comment by WendyDReid1901** [comment]
When I run my script,the memory keep increase,but aiohttp,the memory usasage is stable,I saw someone have faced this issue before,may be need some gc.collect()  # 手动回收垃圾 when closed session

**Comment by WendyDReid1901** [comment]
哥，能加个微信吗？ 目前只有这个神库可以搞定cloudflare

**Comment by lolkda** [comment]
我用async方式进行数百的并发也没有看到大量内存占用
