### ISSUE TITLE
[BUG] https://www.ebay.co.uk/itm/362819968729  ebay link will redirect, allow_redirects=True not work 

### ISSUE THREAD

**Issue by wanzhu6688** [lexiforest/curl_cffi#410]
**Describe the bug**
https://www.ebay.co.uk/itm/362819968729  
ebay link will redirect to a temp webpage,then redirect to correct link,
I have use  allow_redirects=True parameter,not work
**To Reproduce**
```
# Minimal reproducible code, if possible.
# target websites, and request parameters.
```

**Expected behavior**

**Versions**
 - OS: [e.g. linux x64]
 - curl_cffi version [e.g. 0.5.7]
 - `pip freeze` dump

**Additional context**
- Which session are you using? async or sync?
- If using async session, which loop implementation are you using?

**Comment by lexiforest** [comment]
I think you were being redirected to a JS chanllenge page(https://www.ebay.co.uk/splashui/challenge), better IP or other bypass techniques are need to avoid this detection. This is NOT related to curl_cffi.

**Comment by wanzhu6688** [comment]
thks
