### ISSUE TITLE
How to set SSH_COMPRESSION Opt value

### ISSUE THREAD

**Issue by mamaliamir560** [lexiforest/curl_cffi#416]
**How to set _SSH_COMPRESSION_ Opt value?**

I want to set the _SSH_COMPRESSION_ Option and I tested (True, 0, 1) values, but there are value errors. I saw the libcurl documentation, and the values are "1L" or "0L," but I can't use them in Python.

Errors:
`Failed to setopt CurlOpt.SSH_COMPRESSION True, curl: (48)`

**Versions**
 - OS: Linux PC12 6.8.0-47-generic
 - curl_cffi version 0.7.3

**Comment by lexiforest** [comment]
The bundled `libcurl-impersonate` was built without ssh support, so this option is not available. Could you please elaborate on your use case?
