### ISSUE TITLE
Encounter ssl 60 error when curl_cffi + BrightData proxy manager

### ISSUE THREAD

**Issue by pgshow** [lexiforest/curl_cffi#417]
**Describe the bug**
I am using BrightData proxy manager. curl_cffi doesn't work with the below code.
It encounter error: **Failed to perform, curl: (60) SSL: no alternative certificate subject name matches**

this below code, requests part works with verify=False, but cffi_requests deosn't.

```
import os
import time
import requests
from curl_cffi import requests as cffi_requests
from curl_cffi import Curl

proxies = {'http': 'http://149.28.250.62:24000', 'https': 'https://149.28.250.62:24000'}


headers = {
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.33',
}

r1 = requests.get('https://lumtest.com/myip.json', headers=headers, proxies=proxies, verify=False)

print('requests')
print(r1.text)
print(r1.status_code)

time.sleep(3)

r2 = cffi_requests.get('https://lumtest.com/myip.json', headers=headers, proxies=proxies, verify=False)

print('curl_cffi requests')
print(r2.text)
print(r2.status_code)
```

**Versions**
 - OS: Ubuntu 18
 - curl_cffi version 0.8.0
 - BrightData proxy manager

![b336b30f3e3316aacc431ac4a0f0b2f4](https://github.com/user-attachments/assets/3e310a94-3431-4850-8328-14ea6526e50a)

**Comment by pgshow** [comment]
If I set the CurlOpt.PROXY to an HTTP proxy, then curl_cffi  can connect to my ProxyManager server, but the fingerprint is gone.

`from curl_cffi import Curl, CurlOpt, requests

proxies = {'http': 'http://149.28.250.62:24000', 'https': '149.28.250.62:24000'}

# 初始化 Curl 对象
curl = Curl()
curl.setopt(CurlOpt.URL, "https://httpbin.org/ip")
curl.setopt(CurlOpt.SSL_VERIFYPEER, 0)  # 关闭对服务器证书的验证
curl.setopt(CurlOpt.SSL_VERIFYHOST, 0)  # 关闭对主机名的验证
curl.setopt(CurlOpt.PROXY, proxies['http'])  # 设置代理

# 执行请求
curl.perform()`

![0de766bc57320e6167221a3bb2e4fa5c](https://github.com/user-attachments/assets/fea89544-6f78-42fe-b597-c9cad07f5ac1)

![ff7d0309402a4ffb1f277be1b0864dbc](https://github.com/user-attachments/assets/73db47b2-354e-4a7e-a60e-5883bae7b89b)

**Comment by perklet** [comment]
It seems that you ignored the warning messages. Make sure you read through #6.

**Comment by pgshow** [comment]
Yes, I am using curl.setopt to debug ,so there is no warning message.

when I used {'https': 'http://gw.dataimpulse.com:823'} as the proxy, akamai_hash works. but {'https': 'http://149.28.250.62:24017'} doesn't.
I think ProxyManger wraps the request on their software themselves so that akamai_hash is gone.
Let me ask them.

**Comment by pgshow** [comment]
After I deactivated the SSL on ProxyManger, and used the {'https': 'http://149.28.250.62:24017'} as the proxy, the fingerprint is back. So I am sure the curl_cffi and ProxyManger SSL have a conflict.

![0c22abb63ab16ff4a3e54c4559272dca](https://github.com/user-attachments/assets/b700ec26-1626-4be8-8c06-8efe6a2c5e11)

![ddab82eb65797d3b60f8594263cb6e6c](https://github.com/user-attachments/assets/1236016e-6e6b-42aa-a3e4-5bf63323e369)

**Comment by lexiforest** [comment]
The SSL switch you mentioned seems to be some kind of MITM change of the TLS traffic, it will change the TLS traffic entirely. Yes, there is a conflict.
