### ISSUE TITLE
Request Headers 

### ISSUE THREAD

**Issue by lolyinseo** [lexiforest/curl_cffi#420]
According CURL doc https://curl.se/libcurl/c/CURLOPT_HTTPHEADER.html
All headers with empty value should be removed, without replacing with default headers

` If you add a header with no content as in 'Accept:' (no data on the right side of the colon), the internally used header is disabled/removed. With this option you can add new headers, replace internal headers and remove internal headers. To add a header with no content (nothing to the right side of the colon), use the form 'name;' (note the ending semicolon).`

But this will not happen. For example 

`{'Content-Type': ''}`

In the request it becomes like 

`Content-Type: `

Headers like

`{'Content-Type': None}`

Produces a huge number of errors(since you always expect a string)

If I removing the header completely the default Curl header appearing(As it should be according to the documentation).

`Content-Type: application/x-www-form-urlencoded`

suggest that the correct behavior for `{'Some-Header': None}` is remove headers ( set `Some-Header:` for curl), and for `{'Some-Header': ''}` is set `Some-Header;` (note the ending semicolon).

**Comment by lolyinseo** [comment]
> It makes sense to me. Anyway, can you describe a situation where you would want to completely make the `Content-Type` header removed in the request?

not only `Content-Type`, this behavior should apply to all headers. In my case, the server only accepts requests with missing `Content-Type`

**Comment by hectorgarciatorres** [comment]
this is a huge issue, has anyone found a solution?

**Comment by lexiforest** [comment]
Since 0.8.1b8, you can use `{"Name": None}` to disable the `Name` header.
