### ISSUE TITLE
Proxy Configuration Problem

### ISSUE THREAD

**Issue by mominurr** [lexiforest/curl_cffi#421]
**my code:**
```
proxy = f'https://{username}:{password}@{host}:{port}'
response = requests.get(url[0], impersonate="chrome", proxy=proxy, timeout=(10, 10))
```

My proxy provider gives me this format (`proxy = f'https://{username}:{password}@{host}:{port}'`) configuration for proxy. I am using an HTTPS proxy. I read your documentation and also this issue (https://github.com/lexiforest/curl_cffi/issues/6) where I can see that the proxy format: `"http://user@pass:proxy_url"`

But my code is working. So I hope you will fix this issue. 

**code warning:**
```
D:\Developing\W.S-PROJECT\realself.com\env\lib\site-packages\curl_cffi\requests\session.py:965: RuntimeWarning: Make sure you are using https over https proxy, otherwise, the proxy prefix should be 'http://' not 'https://', see: https://github.com/lexiforest/curl_cffi/issues/6
  req, buffer, header_buffer, q, header_recved, quit_now = self._set_curl_options(
```

**Comment by lexiforest** [comment]
Sure, I guess I should make this warning optional. It's pretty annoying when you know what you are doing.

**Comment by lexiforest** [comment]
Warnings are silenced by default since v0.8.1b8.
