### ISSUE TITLE
Why is `server_name` extension not available ?

### ISSUE THREAD

**Issue by novitae** [lexiforest/curl_cffi#423]
**The question**
Why when my `ja3` contains a `0`, it tells me `NotImplementedError: It's unlikely that the server_name(0) extension being changed.` I need my custom impersonation to contain the `server_name`. Is it added automatically ? I've seen that some of the builtin signatures seems to support it (https://github.com/lexiforest/curl-impersonate/blob/325a4ab8ad7f6cc723dee951cf4618103895ffd5/tests/signatures/firefox_98.0_win10.yaml#L48), why does the custom impersonation doesn't support it then ? Thank you.

**Comment by lexiforest** [comment]
The extension `server_name(0)` is the most basic one, it appears almost universally in the Hello packet, so there is no reason to turn it off. I think you accidentally omitted this one in your JA3 string.

The line you highlighted in for another extension, which value is 0, not the server_name extension.
