### ISSUE TITLE
discord bot请求头加了Authorization: Bot xxx，好像被Cloudflare封禁，返回403

### ISSUE THREAD

**Issue by yeyuchen198** [lexiforest/curl_cffi#428]
**The question**

我想用discord bot，来请求某些discord的接口，请求头加了Authorization: Bot xxx，好像会被Cloudflare封禁，返回403，内容为：
{"message": "internal network error", "code": 40333}

我用curl来请求，是正常的。示例如下：
curl -H "Authorization: Bot xxxxxx" https://discord.com/api/v9/channels/xxxxxxxx/messages

我搜了网上别人的案例，发现也有人出现了这种情况（nodejs的）：
https://teratail.com/questions/jn1e2zmiswoz32

**Documentation suggesion**

If the documentation is missing or confusing, add your suggestion here.

**Versions**

 - OS: Windows 11
 - curl_cffi version 0.6.4

**Comment by yeyuchen198** [comment]
impersonate='chrome120'

**Comment by yeyuchen198** [comment]
我这样设置之后，竟然可以了：
impersonate=None

**Comment by lexiforest** [comment]
See here, discord docs: https://discord.com/developers/docs/topics/opcodes-and-status-codes
> 40333 | Cloudflare is blocking your request. This can often be resolved by setting a proper User Agent

It's probably CF is blocking the chrome120 useragent, just use other versions.
