### ISSUE TITLE
Import of curl fails on 32 bit raspberry pi running home assistant - no 32bit binaries in curl package?

### ISSUE THREAD

**Issue by AdrianGarside** [lexiforest/curl_cffi#429]
The import results in this error:
ImportError: Error loading shared library /usr/local/lib/python3.12/site-packages/curl_cffi/_wrapper.abi3.so: Exec format error

**Versions**
 - OS: Raspberry Pi running home assistant
 - curl_cffi 0.7.3

https://github.com/greghesp/ha-bambulab/issues/717

Is there any solution for this?

**Comment by lexiforest** [comment]
Try this pypi: https://piwheels.org/
