### ISSUE TITLE
Tips needed on how to successfully bypass cloudflare?

### ISSUE THREAD

**Issue by AdrianGarside** [lexiforest/curl_cffi#431]
I'm using this to attempt to get past cloudflare with my Home Assistant Bambu Labs printer integration. It authenticates as the user to retrieve printer details as part of initial setup and then it later uses those credentials to get information about in progress prints (such as the rendered image for them).

Initial switch to curl_cffi worked for about 2 days before cloudflare started detecting and blocking again. I hadn't specified a browser to impersonate so I switched to chrome. That worked for about 3 days. Switching to safari17_2_ios works again but it seems each attempt is only going to last a brief while before cloudflare adapts and starts to block again. Eventually and quickly I'll run out of browsers. Is there anything else I can try to avoid cloudflare detecting and blocking my integration?

One observation (with earlier attempts using cloudscraper instead of curl_cffi) that totally stumped me is that in some cases the authentication attempt works from the host but the exact same connection attempt from within the home assistant docker instance was being blocked. That's not yet happening with curl_cffi - it's either working from both or failing for both.

**Comment by lexiforest** [comment]
What were the rate you were trying to authenticate?
