### ISSUE TITLE
get check proxy tcp connection status

### ISSUE THREAD

**Issue by JustRomanBZK** [lexiforest/curl_cffi#437]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JustRomanBZK** [comment]
> Please provide more details on what you want to achieve.

I want a function that will return the status of the connection to the proxy, and a function for if the connection is disconnected to reconnect.

**Comment by lexiforest** [comment]
That's far beyond the scope of a http client, you may find this feature in a framework-ish library.
