### ISSUE TITLE
Add async websocket_client

### ISSUE THREAD

**Issue by ThePhoenix78** [lexiforest/curl_cffi#441]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ThePhoenix78** [comment]
You can use my fork from websocket client that is async to add to your library. It's not the latest up to date version but it does the job


https://github.com/ThePhoenix78/websocket-async

**Comment by lexiforest** [comment]
I don't think your project is related to curl_cffi, feel free to reopen if you have other thoughts.
