### ISSUE TITLE
配置服务端证书，是否可以防止被抓包

### ISSUE THREAD

**Issue by jiangtaoInfoTech** [lexiforest/curl_cffi#442]
session.curl_options = {
    CurlOpt.CAINFO: 'cert.pem',
    CurlOpt.SSL_VERIFYPEER: 1,
    CurlOpt.PROXY_SSL_VERIFYHOST: 2
}
在pycharm下证书检测生效，但是pyinstaller打包后，对应证书文件也能找到，但是一直报错curl_cffi.requests.exceptions.CertificateVerifyError.
这种设置能防止抓包软件抓包吗

**Comment by lexiforest** [comment]
I think you are on the right path, it should work, but I'm really not an expert in pyinstaller.
