### ISSUE TITLE
url编码bug,影响太明显了

### ISSUE THREAD

**Issue by wlfzsd** [lexiforest/curl_cffi#452]
requests库请求正常，用这个库则出错，抓包对比后发现的问题。
curl_cffi库好像会对发送出去的url编码进行解码后重新编码，但是重新编码会出现bug.
比如url中存在{"pid":"LL&use_sdk","tra":"bizType\u0007birthday"}
curl_cffi发送的url编码会带有逗号和&，这导致了他会切断传送参数！

**Comment by wlfzsd** [comment]
```
#import requests
import json
import urllib.parse
from curl_cffi import requests

data = {"pid":"LL&use_sdk", "tra":"bizType\u0007birthday"}
encoded_data = urllib.parse.quote(json.dumps(data))

url = f"https://www.baidu.com/search?q={encoded_data}"
response = requests.get(url, allow_redirects=False)

print(response.url)
```
![Snipaste_2024-12-03_10-28-23](https://github.com/user-attachments/assets/60417401-c80c-4849-be32-b2f1394cbf9a)

**Comment by lexiforest** [comment]
Fixed in 0.7.4.
