### ISSUE TITLE
Using "aiter_content" method in asynchronized and stream mode will cause data loss of content field of the response.

### ISSUE THREAD

**Issue by LostJay** [lexiforest/curl_cffi#456]
Please check the following items before reporting a bug, otherwise it may be closed immediately.

- [x] **This is NOT a site-related "bugs"**, e.g. some site blocks me when using curl_cffi,
    UNLESS it has been verified that the reason is missing pieces in the impersonation.
- [x] A code snippet that can reproduce this bug is provided, even if it's a one-liner.
- [x] Version information will be pasted as below.

**Describe the bug**
When working asynchronously with the curl_cffi API and passing the keyword stream=True to the request method, a coroutine is returned to handle the response. The response object includes an aiter_content method for iterating over the content asynchronously. However, there is a critical issue in determining whether the stream has been fully transmitted, which can result in data loss.

**To Reproduce**
```py
# Minimal reproducible code, like target websites, and request parameters, etc.
from unittest import TestCase, main
from asyncio import run
from random import choice

from curl_cffi.requests import AsyncSession, Response, get
from curl_cffi import __version__

print(f'The current version of curl-cffi is {__version__}')


class AiterIssue(TestCase):
    # It's difficult to find a fixed url for media nowadays, so I use a personal website for this test.
    # But I have tested several temporary links which also results the same.
    resource_url = 'https://lostjay.xyz/music/starboy.m4a',
    test_target_url = choice(resource_url)
    print(f'Testing for {test_target_url}.')

    @staticmethod
    def run_async(func):
        def wrapper(*args, **kwargs):
            return run(func(*args, **kwargs))

        return wrapper

    @run_async
    async def test_aiter(self):
        async with AsyncSession() as session:
            response: Response = await session.get(
                self.test_target_url, headers={'Referer': self.test_target_url}, stream=True)
        streams = response.aiter_content()
        content = b''
        async for chunk in streams:
            content += chunk
        print(f'The length of content is {len(content)}, which used aiter_content method.')

    def test_iter(self):
        response: Response = get(self.test_target_url, headers={'Referer': self.test_target_url}, stream=True)
        streams = response.iter_content()
        content = b''
        for chunk in streams:
            content += chunk
        print(f'The length of content is {len(content)}, which used iter_content method.')


if __name__ == '__main__':
    main()

```

**Expected behavior**
I created a control group and found that the final content length differs between the iter_content method and the aiter_content method.
![Untitled](https://github.com/user-attachments/assets/16a92d40-4455-4f4d-84f6-079cf5f8d5d9)

**Versions**
 - OS: [macOS 13.2.1]
 - curl_cffi version [0.7.4]
 - `pip freeze` 
certifi==2024.8.30
cffi==1.17.1
curl_cffi==0.7.4
pycparser==2.22
typing_extensions==4.12.2

**Additional context**
- Which session are you using? async or sync? both, for creating a control group.
- If using async session, which loop implementation are you using? the default eventloop policy asyncio.unix_events._UnixDefaultEventLoopPolicy
- If you have tried, does this work with other http clients, e.g. `requests`, `httpx` or real browsers.  **No**

**Comment by lexiforest** [comment]
You need to put your for loop inside session. The connection will be closed once session is closed.

**Comment by LostJay** [comment]
> You need to put your for loop inside session. The connection will be closed once session is closed.

First of all, thank you for your reply. However, I noticed that in synchronized mode, the for loop outside the session does not close the connection, which was a bit confusing and misleading to me.

**Comment by perklet** [comment]
Consider it an undefined behavior.

来自手机回复
