### ISSUE TITLE
请问怎么绕过cloudflare的真人验证

### ISSUE THREAD

**Issue by fishTsai20** [lexiforest/curl_cffi#463]
**The question**

- What feature do you find confusing?
- Which site does not work? And you don't have a clue.

**Documentation suggesion**

If the documentation is missing or confusing, add your suggestion here.

**Versions**

If it's related to a specific environment, paste your env info here.

 - OS: [e.g. linux x64]
 - curl_cffi version [e.g. 0.5.7]
 - `pip freeze` dump

`c = requests.get(
        "https://gmgn.ai/api/v1/wallet_holdings/sol/4zu8VpsXXp7ajyDKKmQ1cMaWkWANojcNPi2FV6fdiCuQ",
        impersonate="safari15_5")`
返回403
`b'<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box;margin:0;padding:0}html{line-height:1.15;-webkit-text-size-adjust:100%;color:#313131;font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji}body{display:flex;flex-direction:column;height:100vh;min-height:100vh}.main-content{margin:8rem auto;max-width:60rem;padding-left:1.5rem}@media (width <= 720px){.main-content{margin-top:4rem}}.h2{font-size:1.5rem;font-weight:500;line-height:2.25rem}@media (width <= 720px){.h2{font-size:1.25rem;line-height:1.5rem}}#challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI0IyMEYwMyIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjQjIwRjAzIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+);background-repeat:no-repeat;background-size:contain;padding-left:34px}@media (prefers-color-scheme:dark){body{background-color:#222;color:#d9d9d9}}</style><meta http-equiv="refresh" content="390"></head><body class="no-js"><div class="main-wrapper" role="main"><div class="main-content"><noscript><div class="h2"><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></noscript></div></div><script>(function(){window._cf_chl_opt={cvId: \'3\',cZone: "gmgn.ai",cType: \'interactive\',cRay: \'8f367cce4f939690\',cH: \'XYMm6CTeJSbPj1OAc490Xb3jX9n53W1A30HcRTsIPUs-1734434045-1.2.1.1-pmlWJ0fsPGUn_3EzTbaU0hmQZysP1enTNQkLXxoP7pobY708iZimeg8IYH1ISgAz\',cUPMDTk: "\\/api\\/v1\\/wallet_holdings\\/sol\\/4zu8VpsXXp7ajyDKKmQ1cMaWkWANojcNPi2FV6fdiCuQ?__cf_chl_tk=j_tY7k6OCaGFLaZSAHCsTkxWKDFPgeWZUOhZUG7eyzo-1734434045-1.0.1.1-MIGsOwxRIaKgThkV2WSjSzWHyi1rMAIx9If532PTBT0",cFPWv: \'b\',cITimeS: \'1734434045\',cTTimeMs: \'1000\',cMTimeMs: \'390000\',cTplC: 0,cTplV: 5,cTplB: \'cf\',cK: "",fa: "\\/api\\/v1\\/wallet_holdings\\/sol\\/4zu8VpsXXp7ajyDKKmQ1cMaWkWANojcNPi2FV6fdiCuQ?__cf_chl_f_tk=j_tY7k6OCaGFLaZSAHCsTkxWKDFPgeWZUOhZUG7eyzo-1734434045-1.0.1.1-MIGsOwxRIaKgThkV2WSjSzWHyi1rMAIx9If532PTBT0",md: "HQ2RPFBM1JN1RBPpyj1c5XWek4UM9I84CR28.JjJWTQ-1734434045-1.2.1.1-va6V7eDFdsLbCGrmgmoGnLZWSXPxObLC32w6CkUdp_nY.ZklcyiStr.MxSQF0KIoHwag6rV6FTGY8kGcyKRJeaA1SlppWDOurT1Lg2Hhi4Wc.UGQ2a5YrbwBYPnntfHVmLZP5Bj2DzpUzLdJv422erWhDVDdvJ6aI1JAlrf0aTdxRjXQPoHXCufKB6wzZ8vrTnFiAa8HBwTdo9Vd6Uba2JXevc4Pa8M1N.t9P2hmaTM3RY4h.eUY.Mu36azLGk70vtipceazeM63vSMsIQxv71PoAkqkSz6YQBYoK.Bj7Q2Vqeo1XwZ2Gs2OUYCAo7oZiJAHnJ_HNhc.y6TwegHt6CRTbn9srl.uOblQXkcUF7pCw2qi.mcyTb391DZ_SHEtRJ1jGPxYzu_zZl.CjNUCpR_vXCtUVlvtT_46dFpc_skofpdhVpGnMUG1NnazT5I_.CBEZ.OTX4QWX8JI_1KhBRzww2CwyGTtckV4qHa0Id_Fzy20THi61H7vlIEXqzRX1dtOMPsjySnQ9o7FsAVicURyvDub4du1l9gIdPgeez49EwExndXbpYBp03Ayi2TJhq9xseylW9ad7113n7MJ0CHNV1K8ZcHUWoWljna4Fh_G2edeoGt3jHmfa4sXmtCZESzwZukij06s_KDsvBjTmjWaGRZtr8CmrQ72oD6TKKVgtAX0PwHU6zPWbCWjFoS5I_pz.j7tOMBc6zdvF46ohjXdI9PsVTx0btyfE4WxPrVeWh8ikRcb3jUToFTNPwsyZUAYyztjnDRrm7z4VHL1wbb6rxcwcdQFelNaBMLmJJLBsIiVQ8mYaWSXJpLbPeNt5OmFQG6ngik9Q0E1kalQarIUb4o1D364DEi8.y_AwnOELa1k5YToX_ceIbDEqsWxzRazIRg.yApmFq8mtUC8jvdK3yuyBFGymdDeBad6j7u.vLwMyNdfwffZZKZn7l3jlgh8rKfF.1zVKd.ORvtNwlpwb5oSMe4djZ03_upSk6sRgwl9lebRPWf.rhU_yVSKsb8XtyhcLQ01LwAyLAJKHtIm6habfPfyt2KkQ31_UhYvXITIOyFoLpG.gEvZCedvBsvztQWZ7tZz01fp1zbc74sKTsriaSfqs1Kbk3y3Ik1emJHWWcX27aE03WSa0kTx1zJB74kT5O5iU.07XT1WiznGU32qvitavVk.EBbOh94TVhSpfIKMEhOMju8n2lmK0v8pTZKg8Ug3xT_B892zdbJW8pTCsyDfxDYJS3C7cbXKU7oIn7xVQmOBMQdUZEm1Pbv.ePALuuE8Nr9nfWqsgFpyKV5sdQzsR30tr5Wqx5ZvelvgdRjCa0uv8edKpuYWgH6n0oGdQxHDkofBouZ_6rtbGIDjC5TFKQP7F.uSbxLLeAuPhsABc_8CBJx07XYcxlWjHKWy8_ooUYqPb.IM3aPmxNp8TiPMvzwtV6Vh1gbs9WVG_joAlbkegY4WlhHYJyL5cJT.n_i3Ras.Z6bKfgeC0_aGdmDkevLY8tOnovIqkJp_xTkV2eYknw34kWjLZvsKR1pw1fk46Oz3OdEjBPMxdvQtLFG6EK0vL26kHticOvoJrgJChkxxJdLX76gvXvNK49ByZ7wV3evFeZZ2.vih9EGAjMP4D_dn.Ru.n8YiblErOXFtACG5eflPkdjVA.D1H00t0J5WP.XsvXuCQK_hZdyjmjVj1w5an7TEr3ZQ__su2HbVGl9od3gbETOiQ3s0UzswftrsMtbz70t4oOr3tj.ZN3PImUpdpqrlgrZ8bH2W1qXj32_rlUYmr5hvWFIC2QbJVjNANf7pB26msq8qjjI4FlO4t3WoySI3eIEaotJI57ZF6LP0ju7wPJej86OlWU42pgE8dKpa7f_8dxrFbyD6DFRtS1iMHGWG06VLiVTVPuOMGKpAy0pam.BczPrr3peT8yz7hn5Lge_SuUIn4TDz1YgjODK5nvSSIXW5Cz7DHNMlOUweydV_VPvAqMBY1ClogzOr3qoKYdxcVV1X_4T.sloqG11D4aYgGYcuJlHBIChL1opRtwKrC5hjT5kXi_b5yLeGhcpS2XnDg8rEBnxZOeIDHkMgnXiE.fnGDMtZG6LYk6q1qFeMct2Y",mdrd: "R.NfDMXp31ZKE.46WkkqHCjvKBQ2b88DOgvuFQ5WipQ-1734434045-1.2.1.1-lfIPrLiw.95Uk5Eo8Fl1H37V3SfIpz4pRLEIPnEe5CY8dboOMl0TWy3nCEqH.mTP2oCrmQQR3tGYDVmR7A6e5jyln48JgvBLte3hBMIKFgIHeWy34OcKnf9L4nLAUYwLrtaYWPcJbIAN7okW0SYpIRgk32zTfWjZeFtxR10VWF6xuvZnk0n5sqWXbHi9Ah7ZiSxBz95FnXXeyqG61dflIbQxvbMN31514qHJ_.6XmmZ7m883Sxw_.VBfuU57XMHM6PM8qRvCBjxYbh3R0Yko0k4NyEuNvpnkquEUv1FYlXyAezSAn8BabZ5npUPTRbLadwhF5TVu7vWO06HrL9d44yYajoa.VI007CNNt0mP1oYUB9567eiUY8URrrlj4CrQW87kzfLzn3bOD1eVlVqrnCqeWDItXVCAG_a97So8omlV6IInyc6al0m_G.Ktdbs.w_pZ2GCSMAnG5zdaEX.dFX6cNU5OlD2b5t5r3B0id7EHw2nulD1w3sWE_lGYp45GtaKaTt.bpbRw97GfE5jo9GO_cr6tbZhvl8n8OkUMzyAa15fiXh5a64MO9ij4i9rE8VmYT_coqlbBC5wPcWScusa8GvptAA.76Hq4KjAACqR85RPm7mL17bnQIwBJdSc8umx5FK7HSnuPh9SvUuYWwTrXOuF2Z6KpRwx_ux1PP0DI042oJpcJ_e89INZ6ZUj.YYe2QIVSORTPRTIn9ZwDV52dvwZyfdJGsfWFUHCnWmFcYVI4b9FYe2C.DpgcbjAqKb0c7tAl0xylyUn1EqR00tJtZriiQMbdmJF5IuRY2GX1eeIKUjfaFsIf8iosb.LUK0fPE8lLv5VbsIv859o9t6VEpSfVkHB.5w_nT_kDMwbURMHBCR02CydPGhD4ogveB2J.DXwJnwQ1HhSGSOcdr.Y_.oxi8Fiyo4D1TaP1v4lbI5LNpKN9CqfCCTRYe92h2pOuZRUX1bVWfVKJocHk0lc0rF0FZGYVQU2rg9SYubb6KNptjx_l3pMp9H.qPvZ57SBNW1fSWgZ6ScPSvweE7Ynyt8yaSvBmP.AZURoiG77gFOjksbWavhVAogyRJuxoHui6Rhnl3Cc525AmKRYHMHiZFVfEpKJ9nzx1gCEDrRgmLSmi8OdogJEwqa9._EyuNypO0ltF8HAwDyqKeRNCG6V8Ha5NvEIF1fwj0XBoFp2JkShAknVuQtWjBgR3sYV7sqVoRNQENJo9DXlEmyVau.xNjviM70zuCSaSG22N6RZ8KGJdmQbw7GbF6J5eOfOw9YkW6NySIv2LgA60ThYQx8txjChOwqOqbHVwCPzXViYfbL3grPX2MKcxtyosziCHRMvGPpPWeSGu6jiF.OqlhXIXcw7bfFu1NoM9gHOqJFhiXMqFp_3E6BtJuuvNCmaghUXlZB.NJbHcEBOTl0nxiP5dK9.Ofwr2YFtZGeiH_G2nJ37a7Ww5xVpbYKx8keKNmmvAf8cPImeqWQKPA5ixVm8ZHUUkkK6AzlU.GhyFntmjsQIlkW9Ao2ZHLk_23tUF6uUxVMSr4ieInFB1J2mI2O2AELoIfet.R9BCb20Pdahm5Mek8LKw2Su4rdKK9j0.Y6EVzRLio0P8seQq.KgX.JiaakU6rsOivedF8.DCU7ZlGX4UCO.1GU.8NyfnHovfGhOyjM61IPOpzyA_5xNPCoKJxG0vN5gmU.i4Y2vepq88J3YCvY6z9ofjRVBG.YMZ_0sJtxEIAel.0shQNBXOazFd5ND_xqW.rVKbEryV9HaNYbtNpMugh7AwYIlgThShMQoHxOkgkJejVm_anUIKFemd_EKY.Jy0VGFEukEcUSGSIBVoyZ354KeinPS.bd1IJHZETyOUwBGiOhl9zZ41_Rh5KrJlrj.tqlI4wIzuTKDkjOOp97G4sf0pF6xdZqia0pq7FGi_jY2YTry17XKdp2tpvTl9IojrMefO27Ay06iu6q8slcqratGHf2tswWH6RwUNx1G5L2mb3S.ca6h21Rf4t5gieS8b29sX1PJ.b9NRKAFwIGRs922VtRjEEbAjSzDfqdmDsxzWpU8pOzefeHITqh19zrKkZ0NV2t_J57iYPrktV2_fIWM0xTETRz9HlheuXu1PCcGkm7ot.fBoyIHWU4rJVeGhDTyoaGrR8V5mP.gu80T3ZkU0DChbJbMi3NKmNPm4V.V9WbHkJH9tA9Xvml.i8xuT8fMzjPawOzpEg_7n1B_FcqDEFHhhfsOVpEutShLQuEvsyaIoe5mm_TG6jZeM8MGQfuv5d2ocZ5LNM_AVTCdT6n2h5TBe90dAVSfI39e3uWbTt_Hl3.ArUw"};var cpo = document.createElement(\'script\');cpo.src = \'/cdn-cgi/challenge-platform/h/b/orchestrate/chl_page/v1?ray=8f367cce4f939690\';window._cf_chl_opt.cOgUHash = location.hash === \'\' && location.href.indexOf(\'#\') !== -1 ? \'#\' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === \'\' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf(\'?\') !== -1 ? \'?\' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null, "\\/api\\/v1\\/wallet_holdings\\/sol\\/4zu8VpsXXp7ajyDKKmQ1cMaWkWANojcNPi2FV6fdiCuQ?__cf_chl_rt_tk=j_tY7k6OCaGFLaZSAHCsTkxWKDFPgeWZUOhZUG7eyzo-1734434045-1.0.1.1-MIGsOwxRIaKgThkV2WSjSzWHyi1rMAIx9If532PTBT0" + window._cf_chl_opt.cOgUHash);cpo.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName(\'head\')[0].appendChild(cpo);}());</script><script defer src="https://static.cloudflareinsights.com/beacon.min.js/vcd15cbe7772f49c399c6a5babf22c1241717689176015" integrity="sha512-ZpsOmlRQV6y907TI0dKBHq9Md29nnaEIPlkf84rnaERnq6zvWvPUqr2ft8M1aS28oN72PdrCzSjY4U6VaAw1EQ==" data-cf-beacon=\'{"rayId":"8f367cce4f939690","serverTiming":{"name":{"cfExtPri":true,"cfL4":true,"cfSpeedBrain":true,"cfCacheStatus":true}},"version":"2024.10.5","token":"5a932bf601cf4a28913fd6bf1d5fd4bd"}\' crossorigin="anonymous"></script>\n</body></html>'`

**Comment by lexiforest** [comment]
See the [FAQ section](https://curl-cffi.readthedocs.io/en/latest/faq.html#can-i-bypass-cloudflare-with-this-project-or-any-other-specific-site) in docs. This kind of question is better suited in our telegram/discord/wechat channels, where you may find other users offering paid solutions.
